---
language: cpp
sudo: false

env:
  - PLATFORM=arduino:avr:leonardo
  - PLATFORM=arduino:avr:uno
  - PLATFORM=arduino:sam:arduino_due_x
  - PLATFORM=arduino:samd:arduino_zero_native

matrix:
  fast_finish: true

before_install:
  - source <(curl -SLs https://gist.githubusercontent.com/tomasbasham/e9ace873c23f8f0f00cd31b22f141111/raw) # install.sh

script:
  - build_examples

notifications:
  email: false
  slack:
    secure: "chBORfIngpeNqSgkcjZi5nreUV5GODJW0vehpwwJk/a6lahLFenXGhkcmvoeKyCE3myfrXXsCd9/lNuYr/U9L2Jcgnl/RHR1xpJcpD85P1zvuzpq4Rp4Qir3sfvXWYodvz1iKdsy8TYqSZyvj4WiCRsdJhGpyot/jgcjCp3lUSNH0ZyvqJNkZequei1T/b0espDEM6dY5+9RvljrY9rvfOgtbnIEhwsnl93+Uik0E4eM01bK/PBdK2o68WqzaAm2p5SgdDeO/EqQTKlWgsXT5/qdQpMfeLRx8e3lyjrJ77cBOgjdMs2ryhGHp7CumkY4ArLI9FBgBClaUYtWuH5jBu0TX4nUTUW3VMprPdXu7iFokbFONO/lIrK4dbWbb5ypy4IJbYkYTmxffP/Audpihitz4JNf2GYXik4PeZR4ggGau/p8iu+JU3hpzdh0JCPI3T2UVikqSTrWNmkgnTd+xeyCoXrimdwgc6/kMaV13hLbUS17s9RaPHtBt2TijrkIwQnv5YagM+yn6El9XwkDVOaK99IzFLAAquJn/Uc5wovEk/yKfppcc83e75r6hvZIgCtFZXzCj6RN3QbaM8+mpyFpaYR3v6dA6u9feLSwWiWoTJRgUwQFWXOLsYF59OXagthHW2XXoPr22wwsdNq6/+eRfFShD4XZD37CeNTY3HI="
